services:
  - type: web
    name: krishi-sahayak
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn complete_app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: GROQ_API_KEY
        sync: false
      - key: ACCUWEATHER_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SESSION_SECRET
        generateValue: true